version: '3'

services:
  minecraft:
    build: .
    image: ewized/mcbr:latest
    ports:
      - 25566:25565
      - 5005:5005
    volumes:
      - ./build/libs/mcbr-1.0.0-SNAPSHOT-all.jar:/opt/minecraft/mods/mcbr.jar
      - ./run/logs:/opt/minecraft/logs
      - ./run/crash-reports:/opt/minecraft/crash-reports
